version: 2

models:
  - name: dim_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null


  - name: fct_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: int_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null


  - name: int_core_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
